from unittest import TestCase
from unittest.mock import patch
from levels import fall
from text import input_color


class Test(TestCase):

    @patch('random.randrange', side_effect=[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
                                            4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
                                            4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4])
    def test_fall_all_same_spot(self, _):
        mobs = [{"name": "meteor", "x_coordinate": 0, "y_coordinate": 0, "alive": True,
                 "symbol": input_color(" M ", "RED"),
                 "ai": ["fall", "countdown"], "time left": 50}]
        map_key = {(0, 0): "character symbol"}
        fall({"name": "meteor", "x_coordinate": 0, "y_coordinate": 0, "alive": True,
              "symbol": input_color(" M ", "RED"),
              "ai": ["fall", "countdown"], "time left": 50}, mobs, map_key)
        expected = [{"name": "meteor", "x_coordinate": 0, "y_coordinate": 0, "alive": True,
                     "symbol": input_color(" M ", "RED"),
                     "ai": ["fall", "countdown"], "time left": 50},
                    {'name': 'meteor', 'x_coordinate': 4, 'y_coordinate': 4, 'alive': True,
                     'symbol': input_color(" M ", "RED"), 'id': 1,
                     'ai': ['countdown', 'shoot'], 'time left': 50},
                    {'name': 'meteor', 'x_coordinate': 4, 'y_coordinate': 4, 'alive': True,
                     'symbol': input_color(" M ", "RED"), 'id': 2,
                     'ai': ['countdown', 'shoot'], 'time left': 50},
                    {'name': 'meteor', 'x_coordinate': 4, 'y_coordinate': 4, 'alive': True,
                     'symbol': input_color(" M ", "RED"), 'id': 3,
                     'ai': ['countdown', 'shoot'], 'time left': 50},
                    {'name': 'meteor', 'x_coordinate': 4, 'y_coordinate': 4, 'alive': True,
                     'symbol': input_color(" M ", "RED"), 'id': 4,
                     'ai': ['countdown', 'shoot'], 'time left': 50},
                    {'name': 'meteor', 'x_coordinate': 4, 'y_coordinate': 4, 'alive': True,
                     'symbol': input_color(" M ", "RED"), 'id': 5,
                     'ai': ['countdown', 'shoot'], 'time left': 50},
                    {'name': 'meteor', 'x_coordinate': 4, 'y_coordinate': 4, 'alive': True,
                     'symbol': input_color(" M ", "RED"), 'id': 6,
                     'ai': ['countdown', 'shoot'], 'time left': 50},
                    {'name': 'meteor', 'x_coordinate': 4, 'y_coordinate': 4, 'alive': True,
                     'symbol': input_color(" M ", "RED"), 'id': 7,
                     'ai': ['countdown', 'shoot'], 'time left': 50},
                    {'name': 'meteor', 'x_coordinate': 4, 'y_coordinate': 4, 'alive': True,
                     'symbol': input_color(" M ", "RED"), 'id': 8,
                     'ai': ['countdown', 'shoot'], 'time left': 50},
                    {'name': 'meteor', 'x_coordinate': 4, 'y_coordinate': 4, 'alive': True,
                     'symbol': input_color(" M ", "RED"), 'id': 9,
                     'ai': ['countdown', 'shoot'], 'time left': 50},
                    {'name': 'meteor', 'x_coordinate': 4, 'y_coordinate': 4, 'alive': True,
                     'symbol': input_color(" M ", "RED"), 'id': 10,
                     'ai': ['countdown', 'shoot'], 'time left': 50},
                    {'name': 'meteor', 'x_coordinate': 4, 'y_coordinate': 4, 'alive': True,
                     'symbol': input_color(" M ", "RED"), 'id': 11,
                     'ai': ['countdown', 'shoot'], 'time left': 50},
                    {'name': 'meteor', 'x_coordinate': 4, 'y_coordinate': 4, 'alive': True,
                     'symbol': input_color(" M ", "RED"), 'id': 12,
                     'ai': ['countdown', 'shoot'], 'time left': 50},
                    {'name': 'meteor', 'x_coordinate': 4, 'y_coordinate': 4, 'alive': True,
                     'symbol': input_color(" M ", "RED"), 'id': 13,
                     'ai': ['countdown', 'shoot'], 'time left': 50},
                    {'name': 'meteor', 'x_coordinate': 4, 'y_coordinate': 4, 'alive': True,
                     'symbol': input_color(" M ", "RED"), 'id': 14,
                     'ai': ['countdown', 'shoot'], 'time left': 50},
                    {'name': 'meteor', 'x_coordinate': 4, 'y_coordinate': 4, 'alive': True,
                     'symbol': input_color(" M ", "RED"), 'id': 15,
                     'ai': ['countdown', 'shoot'], 'time left': 50},
                    {'name': 'meteor', 'x_coordinate': 4, 'y_coordinate': 4, 'alive': True,
                     'symbol': input_color(" M ", "RED"), 'id': 16,
                     'ai': ['countdown', 'shoot'], 'time left': 50},
                    {'name': 'meteor', 'x_coordinate': 4, 'y_coordinate': 4, 'alive': True,
                     'symbol': input_color(" M ", "RED"), 'id': 17,
                     'ai': ['countdown', 'shoot'], 'time left': 50},
                    {'name': 'meteor', 'x_coordinate': 4, 'y_coordinate': 4, 'alive': True,
                     'symbol': input_color(" M ", "RED"), 'id': 18,
                     'ai': ['countdown', 'shoot'], 'time left': 50},
                    {'name': 'meteor', 'x_coordinate': 4, 'y_coordinate': 4, 'alive': True,
                     'symbol': input_color(" M ", "RED"), 'id': 19,
                     'ai': ['countdown', 'shoot'], 'time left': 50},
                    {'name': 'meteor', 'x_coordinate': 4, 'y_coordinate': 4, 'alive': True,
                     'symbol': input_color(" M ", "RED"), 'id': 20,
                     'ai': ['countdown', 'shoot'], 'time left': 50}]
        expected_map = {(0, 0): "character symbol", (4, 4): input_color(" M ", "RED")}
        self.assertEqual(mobs, expected)
        self.assertEqual(map_key, expected_map)

    @patch('random.randrange', side_effect=[-4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4,
                                            -4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4,
                                            -4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4,
                                            -4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4,
                                            -4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4])
    def test_fall_outside_map(self, _):
        mob = {"name": "meteor", "x_coordinate": 0, "y_coordinate": 0, "alive": True,
               "symbol": input_color(" M ", "RED"),
               "ai": ["fall", "countdown"], "time left": 50}
        mobs = [mob]
        map_key = {(0, 0): "character symbol"}
        fall(mob, mobs, map_key)
        expected = [{"name": "meteor", "x_coordinate": 0, "y_coordinate": 0, "alive": True,
                     "symbol": input_color(" M ", "RED"),
                     "ai": ["fall", "countdown"], "time left": 50},
                    {'name': 'meteor', 'x_coordinate': -4, 'y_coordinate': -4, 'alive': True,
                     'symbol': input_color(" M ", "RED"), 'id': 1,
                     'ai': ['countdown', 'shoot'], 'time left': 50},
                    {'name': 'meteor', 'x_coordinate': -4, 'y_coordinate': -4, 'alive': True,
                     'symbol': input_color(" M ", "RED"), 'id': 2,
                     'ai': ['countdown', 'shoot'], 'time left': 50},
                    {'name': 'meteor', 'x_coordinate': -4, 'y_coordinate': -4, 'alive': True,
                     'symbol': input_color(" M ", "RED"), 'id': 3,
                     'ai': ['countdown', 'shoot'], 'time left': 50},
                    {'name': 'meteor', 'x_coordinate': -4, 'y_coordinate': -4, 'alive': True,
                     'symbol': input_color(" M ", "RED"), 'id': 4,
                     'ai': ['countdown', 'shoot'], 'time left': 50},
                    {'name': 'meteor', 'x_coordinate': -4, 'y_coordinate': -4, 'alive': True,
                     'symbol': input_color(" M ", "RED"), 'id': 5,
                     'ai': ['countdown', 'shoot'], 'time left': 50},
                    {'name': 'meteor', 'x_coordinate': -4, 'y_coordinate': -4, 'alive': True,
                     'symbol': input_color(" M ", "RED"), 'id': 6,
                     'ai': ['countdown', 'shoot'], 'time left': 50},
                    {'name': 'meteor', 'x_coordinate': -4, 'y_coordinate': -4, 'alive': True,
                     'symbol': input_color(" M ", "RED"), 'id': 7,
                     'ai': ['countdown', 'shoot'], 'time left': 50},
                    {'name': 'meteor', 'x_coordinate': -4, 'y_coordinate': -4, 'alive': True,
                     'symbol': input_color(" M ", "RED"), 'id': 8,
                     'ai': ['countdown', 'shoot'], 'time left': 50},
                    {'name': 'meteor', 'x_coordinate': -4, 'y_coordinate': -4, 'alive': True,
                     'symbol': input_color(" M ", "RED"), 'id': 9,
                     'ai': ['countdown', 'shoot'], 'time left': 50},
                    {'name': 'meteor', 'x_coordinate': -4, 'y_coordinate': -4, 'alive': True,
                     'symbol': input_color(" M ", "RED"), 'id': 10,
                     'ai': ['countdown', 'shoot'], 'time left': 50},
                    {'name': 'meteor', 'x_coordinate': -4, 'y_coordinate': -4, 'alive': True,
                     'symbol': input_color(" M ", "RED"), 'id': 11,
                     'ai': ['countdown', 'shoot'], 'time left': 50},
                    {'name': 'meteor', 'x_coordinate': -4, 'y_coordinate': -4, 'alive': True,
                     'symbol': input_color(" M ", "RED"), 'id': 12,
                     'ai': ['countdown', 'shoot'], 'time left': 50},
                    {'name': 'meteor', 'x_coordinate': -4, 'y_coordinate': -4, 'alive': True,
                     'symbol': input_color(" M ", "RED"), 'id': 13,
                     'ai': ['countdown', 'shoot'], 'time left': 50},
                    {'name': 'meteor', 'x_coordinate': -4, 'y_coordinate': -4, 'alive': True,
                     'symbol': input_color(" M ", "RED"), 'id': 14,
                     'ai': ['countdown', 'shoot'], 'time left': 50},
                    {'name': 'meteor', 'x_coordinate': -4, 'y_coordinate': -4, 'alive': True,
                     'symbol': input_color(" M ", "RED"), 'id': 15,
                     'ai': ['countdown', 'shoot'], 'time left': 50},
                    {'name': 'meteor', 'x_coordinate': -4, 'y_coordinate': -4, 'alive': True,
                     'symbol': input_color(" M ", "RED"), 'id': 16,
                     'ai': ['countdown', 'shoot'], 'time left': 50},
                    {'name': 'meteor', 'x_coordinate': -4, 'y_coordinate': -4, 'alive': True,
                     'symbol': input_color(" M ", "RED"), 'id': 17,
                     'ai': ['countdown', 'shoot'], 'time left': 50},
                    {'name': 'meteor', 'x_coordinate': -4, 'y_coordinate': -4, 'alive': True,
                     'symbol': input_color(" M ", "RED"), 'id': 18,
                     'ai': ['countdown', 'shoot'], 'time left': 50},
                    {'name': 'meteor', 'x_coordinate': -4, 'y_coordinate': -4, 'alive': True,
                     'symbol': input_color(" M ", "RED"), 'id': 19,
                     'ai': ['countdown', 'shoot'], 'time left': 50},
                    {'name': 'meteor', 'x_coordinate': -4, 'y_coordinate': -4, 'alive': True,
                     'symbol': input_color(" M ", "RED"), 'id': 20,
                     'ai': ['countdown', 'shoot'], 'time left': 50}]
        expected_map = {(0, 0): "character symbol"}
        self.assertEqual(mobs, expected)
        self.assertEqual(map_key, expected_map)

